### ISSUE TITLE
Embed Maps within Local Non-profit Websites

### ISSUE THREAD

**Issue by allella** [hackgvl/OpenData#51]
The tree planting map layer is an earlier example of how we can embed a real-time map preview that sources from "public" map layers.

See the [TreesUpstate plantings page](https://www.treesupstate.org/who-we-are/what-we-do-2/treesgreenville-plantings/
) as an example.

TreesUpstate planting information within a spreadsheet, but they also get a dynamic and real-time map of that information as a bonus.  Plus, anybody else can [point their mapping project / tool at the same GeoJSON link and leverage this same info in real-time](https://data.openupstate.org/map/tree-planting-sites).

Another target would be LiveWell Greenville's Parks references to iMAPs. We could easily map layers that source data from  iMAP data into sites like this and it could help the non-profit and promote iMAP's authority as a maintainer of this critical data.

![image](https://user-images.githubusercontent.com/1777776/93006479-e1908d80-f52a-11ea-8c5f-bc39b9f9af6a.png)

**Comment by allella** [comment]
@pamelawoodbrowne do you still have contact info for @BethanyWinston?

She was an SC Codes student and seems to be the [editor of KiddingAroundGreenville](https://kiddingaroundgreenville.com/about).

They have a farmer's market page and I'd like to reach out to see about making the content owner of that page a maintainer for the farmer's market map and then offer to embed the map as an iframe in their site.

**Comment by BethanyWinston** [comment]
Hi Jim,
My email is bethany@kiddingaroundgreenville.com if you would like to email
me directly. Thanks so much!
